global:
  #janela de obtenção de dados e de espera
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  #arquivo com a configuração dos alertas
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: 'observability'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "host.docker.internal:8081"
